apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: notes-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
